# Generated by Django 5.1.2 on 2024-11-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0002_hardwaredata_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HardWaredata',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='battery_level',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensordata',
            name='water_level',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
